### ISSUE TITLE
Is this project dead?

### ISSUE THREAD

**Issue by xserve98** [gowww/app#10]
Hi,

There is not activity since long time on this project, neither on Issues, nor Pull Requests. So, a simple question, is this project DEAD?

**Comment by xthezealot** [comment]
No, just on a long "stand by". ⏱ 

I'm focused on other projects for now and the next year.
But I know I'll need this package in the next steps of these projects so it will certainly be revived. 🔥

Meanwhile, issues are still handled and contributions are welcome!
