### ISSUE TITLE
[WIP]? I'd like to help!

### ISSUE THREAD

**Issue by ijsnow** [gowww/app#2]
Hello! I haven't landed on a web framework in Go that I've liked everything about so far. Each one either has some functionality that I wish it had or it has way too much functionality. I stumbled upon your router library and have [messed  around a little](https://github.com/ijsnow/rtr) with it. It was my attempt at putting together what I needed as a mini framework while I was waiting on this one! I've looked through all of the code and I think this may be the best choice for what I like in a framework. 

I'd love to help get it out of the [WIP] state if you'd like some help! Have anything that is outstanding that I could take a crack at?

**Comment by xthezealot** [comment]
Hi and thank you!

What prevents me from removing the `[WIP]` flag actually:

- Lack of documentation
- Inexistent testing
- High risk of API breakage

Docs are updated when I have time (generally several days after code implementation).
Writing tests is boring, but you're welcome to write some and make a PR. :)
And for the API instability, I don't think anyone can help much (see below).

> [...] or it has way too much functionality.

Over time, I can't guarantee that you'll not be disappointed.
The other *gowww* packages are very generic and have maximum compatibility with the standard library.
That's not the case of this framework, which has been mainly started for speeding up my workflow.
When I push some code here, I respond to only 2 questions:

- Is it a functionality I expect to reuse in the future?
- Is it the fastest way to reuse it?

That leads to a very opinionated package à la Ruby on Rails (but maybe that's the definition of a framework for some of us):

- Custom `Handler` and `Context` types
- Templates in the `views` directory, not configurable
- Static files in the `static` directory, not configurable
- Built-in i18n
- Built-in cookie encryption

That said, if you still want to contribute, you can post some feature propositions you'd like to see here.
Or you can make a well-tested, generic package that we can transfer in the *gowww* organization and integrate in this framework.

What I'd like to implement now (preferably with GopherJS):

- For development:
  - Live reloading
- For production:
  - Hot code reloading
  - A helper for live data updates (basically, syntactic sugar over websockets)
